### ISSUE TITLE
meta.retrieval fails with NA/NA_assembly_stats.txt

### ISSUE THREAD

**Issue by thisisdomi** [ropensci/biomartr#72]
Hello,

many thanks for the great package! 
I am trying to retrieve genome sizes for a group of bacteria as such:
bac_more.gc <- biomartr::meta.retrieval(kingdom = "bacteria", 
                                   group = "Actinobacteria",
                                   db      = "refseq", 
                                   type    = "assemblystats", 
                                   combine = TRUE)

The command runs fine until the error message. Is there a way to skip the NA/NA entry?

Many thanks and all the best,
Dominik

##error
Starting assembly quality stats retrieval of 'Collinsella aerofaciens' from refseq ...

The FTP link: 'NA/NA_assembly_stats.txt' seems not to be available at the moment. This might be due to an instable internet connection, a firewall issue, or wrong organism name. Could you please try to re-run the function to see whether it works now?
Genome assembly quality stats file download completed!
The FTP link: 'NA/md5checksums.txt' seems not to be available at the moment. This might be due to an instable internet connection, a firewall issue, or wrong organism name. Could you please try to re-run the function to see whether it works now?
The download session seems to have timed out at the FTP site 'NA/NA_assembly_stats.txt'. This could be due to an overload of queries to the databases. Please restart this function to continue the data retrieval process or wait for a while before restarting this function in case your IP address was logged due to an query overload on the server side.
The assembly statistics file of 'Collinsella_aerofaciens' has been downloaded to 'bacteria' and has been named 'Collinsella_aerofaciens_assembly_stats_refseq.txt'.
Fehler: 'bacteria/Collinsella_aerofaciens_assembly_stats_refseq.txt' does not exist in current working directory 

## session info
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /storage/beegfs/home/s_dmerges/anaconda3/envs/rstudio/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8   
 [6] LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2 treemapify_2.5.5   stringr_1.4.0      purrr_0.3.2        tidyr_1.1.2        pheatmap_1.0.12    ggpubr_0.4.0       ggplot2_3.3.3     
 [9] reshape2_1.4.4     dplyr_1.0.4        biomaRt_2.42.1    

loaded via a namespace (and not attached):
 [1] Biobase_2.46.0       httr_1.4.0           bit64_0.9-7          carData_3.0-4        assertthat_0.2.1     askpass_1.0          stats4_3.6.1        
 [8] BiocFileCache_1.10.2 blob_1.2.1           cellranger_1.1.0     yaml_2.2.0           progress_1.2.0       pillar_1.4.7         RSQLite_2.2.3       
[15] backports_1.1.4      downloader_0.4       glue_1.4.2           digest_0.6.18        XVector_0.26.0       ggsignif_0.6.0       colorspace_2.0-0    
[22] plyr_1.8.6           XML_3.99-0.3         pkgconfig_2.0.2      broom_0.7.4          haven_2.1.0          zlibbioc_1.32.0      scales_1.1.1        
[29] openxlsx_4.2.3       rio_0.5.16           tibble_3.0.6         openssl_1.3          generics_0.0.2       IRanges_2.20.2       car_3.0-10          
[36] ellipsis_0.3.1       cachem_1.0.4         withr_2.4.1          BiocGenerics_0.32.0  cli_2.3.0            magrittr_1.5         crayon_1.3.4        
[43] readxl_1.3.1         memoise_2.0.0        fansi_0.4.0          rstatix_0.7.0        forcats_0.4.0        foreign_0.8-71       tools_3.6.1         
[50] data.table_1.13.6    prettyunits_1.0.2    hms_0.4.2            lifecycle_1.0.0      S4Vectors_0.24.4     munsell_0.5.0        zip_2.1.1           
[57] AnnotationDbi_1.48.0 Biostrings_2.54.0    compiler_3.6.1       rlang_0.4.10         RCurl_1.95-4.12      grid_3.6.1           rstudioapi_0.10     
[64] rappdirs_0.3.1       bitops_1.0-6         gtable_0.3.0         abind_1.4-5          DBI_1.1.1            curl_3.3             R6_2.4.0            
[71] utf8_1.1.4           fastmap_1.1.0        bit_1.1-14           biomartr_1.0.2       readr_1.3.1          stringi_1.4.3        parallel_3.6.1      
[78] Rcpp_1.0.6           vctrs_0.3.6          ggfittext_0.9.1      dbplyr_1.4.0         tidyselect_1.1.0

**Comment by HajkD** [comment]
Hi Dominik,

Many thanks for your question and I am happy to hear that you find `biomartr` useful.

This error should be the result of a terminated internet connection or due to some query tracker on the NCBI server side. 

Have you tried re-running the same function? It will pick up at the position where it left off.

I am running the same function on my server and it also terminated at some point, but I am re-running it until I am through and will send you the log file for you to have a reference.

I hope this helps.

Cheers,
Hajk

**Comment by HajkD** [comment]
Hi Dominik,

I found the issue with the query.

It is due to a wrong entry on the NCBI side.

```r
bacteria_file <- biomartr::listGroups(kingdom = "bacteria",
                                      db = "refseq",
                                      details = TRUE)


bacteria_summary <-
  biomartr::getSummaryFile(db = "refseq", kingdom = "bacteria")

Caerofaciens <-
  dplyr::filter(bacteria_summary, organism_name == "Collinsella aerofaciens")

dplyr::filter(Caerofaciens, refseq_category == "representative genome")$ftp_path
```
```
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/670/795/GCF_015670795.1_ASM1567079v1
```

The correct address should be `https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/670/795/GCF_015670795.1_ASM1567079v1`.

Since you found the issue, would you mind notifying the NCBI help desk?

I would have to do some extensive research to check for how many other species this is the case, but simply replacing all `ftp://ftp.ncbi.nlm.nih.gov/` by `https://ftp.ncbi.nlm.nih.gov/` will probably not be a good solution.

I will see if I find another way to work around this in the meantime.

Cheers,
Hajk

**Comment by HajkD** [comment]
Hi Dominik,

Setting `reference = TRUE` should do the trick.

```r
bac_more.gc <- biomartr::meta.retrieval(kingdom = "bacteria",
                                        group = "Actinobacteria",
                                        db = "refseq",
                                        type = "assemblystats",
                                        combine = TRUE, 
                                        reference = TRUE)
```

It seems NCBI doesn't provide FTP paths for non-reference versions of `Collinsella aerofaciens`. 

I will check whether it makes to test for this case internally in the functions.

Does this help?

Cheers,
Hajk

**Comment by HajkD** [comment]
This issue is fixed now by adding the filter rule `!is.na(ftp_path)` into all `get*()` functions.

Hence, you should be able to run your initial code with `reference = FALSE` (default) without problems
after installing the developer version of `biomartr`.

```r
bac_more.gc <- biomartr::meta.retrieval(kingdom = "bacteria",
group = "Actinobacteria",
db = "refseq",
type = "assemblystats",
combine = TRUE)
```

Let me know if this works for you.

Cheers,
Hajk

**Comment by thisisdomi** [comment]
Hi Hajk,

awesome, many thanks for your fast replies! 
I updated to dev as you suggested. The code ran fine now, until a new error appeared. Do you have an idea where this is coming from now?

Starting assembly quality stats retrieval of 'Kitasatospora cineracea' from refseq ...

Genome assembly quality stats file download completed!
Checking md5 hash of file: bacteria/Kitasatospora_cineracea_md5checksums.txt ...
The md5 hash of file 'bacteria/Kitasatospora_cineracea_md5checksums.txt' matches!
Fehler in readr::write_tsv(doc, file = file.path(path, paste0("doc_", local.org,  :
  unbenutztes Argument (file = file.path(path, paste0("doc_", local.org, "_db_", db, ".tsv")))


> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /storage/beegfs/home/s_dmerges/anaconda3/envs/rstudio/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] biomaRt_2.42.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6           XVector_0.26.0       pillar_1.4.7
 [4] compiler_3.6.1       dbplyr_1.4.0         bitops_1.0-6
 [7] zlibbioc_1.32.0      prettyunits_1.0.2    tools_3.6.1
[10] progress_1.2.0       digest_0.6.18        bit_1.1-14
[13] tibble_3.0.6         RSQLite_2.2.3        memoise_2.0.0
[16] BiocFileCache_1.10.2 lifecycle_1.0.0      pkgconfig_2.0.2
[19] rlang_0.4.10         DBI_1.1.1            curl_3.3
[22] parallel_3.6.1       fastmap_1.1.0        downloader_0.4
[25] biomartr_1.0.2       stringr_1.4.0        httr_1.4.0
[28] dplyr_1.0.4          Biostrings_2.54.0    rappdirs_0.3.1
[31] generics_0.0.2       S4Vectors_0.24.4     vctrs_0.3.6
[34] askpass_1.0          IRanges_2.20.2       hms_0.4.2
[37] tidyselect_1.1.0     stats4_3.6.1         bit64_0.9-7
[40] glue_1.4.2           Biobase_2.46.0       R6_2.4.0
[43] AnnotationDbi_1.48.0 XML_3.99-0.3         readr_1.3.1
[46] purrr_0.3.2          blob_1.2.1           magrittr_1.5
[49] ellipsis_0.3.1       BiocGenerics_0.32.0  assertthat_0.2.1
[52] stringi_1.4.3        RCurl_1.95-4.12      openssl_1.3
[55] cachem_1.0.4         crayon_1.3.4

**Comment by HajkD** [comment]
Hi Dominik,

It seems like you have an older version of the `readr` package installed.
You will need version >= 1.4.0. I also made this explicit now in the `DESCRIPTION` file.

Does it work for you now?

Cheers,
Hajk

**Comment by thisisdomi** [comment]
Hi Hajk,

many thanks, updating readr fixed this issue and the retrieval of the Actinobacteria group is running fine (using the command below).

`bac_more.gc <- biomartr::meta.retrieval(kingdom = "bacteria",
group = "Actinobacteria",
db = "refseq",
type = "assemblystats",
combine = TRUE,
reference = TRUE)`

Surprisingly the same command targeting the "Bacteroidetes/Chlorobi" group still fails in a similar way.

`> bac_more.gc <- biomartr::meta.retrieval(kingdom = "bacteria",
+                                         group = "Bacteroidetes/Chlorobi group",
+                                         db      = "refseq",
+                                         type    = "assemblystats",
+                                         combine = TRUE,
+                                         reference = TRUE)`

`Starting assembly quality stats retrieval of 'Bacteroides uniformis' from refseq ...


|===================================================================| 100% 61 MB
The FTP link: 'NA/NA_assembly_stats.txt' seems not to be available at the moment. This might be due to an instable internet connection, a firewall issue, or wrong organism name. Could you please try to re-run the function to see whether it works now?`

Checking the entry with your code, reveals a NA in the FTP entry.

`> bacteria_file <- biomartr::listGroups(kingdom = "bacteria",
+                                       db = "refseq",
+                                       details = TRUE)
> bacteria_summary <-
+   biomartr::getSummaryFile(db = "refseq", kingdom = "bacteria")
|===================================================================| 100% 60 MB
> Caerofaciens <-
+   dplyr::filter(bacteria_summary, organism_name == "Bacteroides uniformis")
> dplyr::filter(Caerofaciens, refseq_category == "representative genome")$ftp_path
[1] NA
> dplyr::filter(Caerofaciens, refseq_category == "representative genome")
# A tibble: 1 x 21
  assembly_access… bioproject biosample wgs_master refseq_category taxid
  <chr>            <chr>      <chr>     <chr>      <chr>           <int>
1 GCF_001406095.1  PRJNA2241… SAMEA354… CYYO00000… representative…   820
# … with 15 more variables: species_taxid <int>, organism_name <chr>,
#   infraspecific_name <chr>, isolate <chr>, version_status <chr>,
#   assembly_level <chr>, release_type <chr>, genome_rep <chr>,
#   seq_rel_date <date>, asm_name <chr>, submitter <chr>,
#   gbrs_paired_asm <chr>, paired_asm_comp <chr>, ftp_path <chr>,
#   excluded_from_refseq <chr>`

Many thanks again and cheers,
Dominik

**Comment by HajkD** [comment]
Hi Dominik,

It seems like NCBI has `NA` FTP paths even for their reference genomes... that is not very good practice. Anyway, I am
now also filtering for `!is.na(ftp_path)` in the reference genome case. For `reference = FALSE` it should have worked already. Now (after installing the new version on GitHub) it should also work for `reference = TRUE`.

Cheers,
Hajk

**Comment by thisisdomi** [comment]
Good Morning Hajk,

awesome, many thanks! Works like a charm now. Do you think, I should report this issue at NCBI?

Cheers,
Dominik

**Comment by HajkD** [comment]
I am very happy that it works now, Dominik :-)

Thank you very much for making me aware of this and it would be fantastic if you could report this at NCBI or at least
mention that choosing to inconsistently add NAs into FTP paths creates a lot of issues for computational automated processing of their data.

Many thanks and please let me know if there are other such drawbacks that we can solve!

Cheers,
Hajk
